### ISSUE TITLE
Feature: User can search for nearby restaurants using filters.

### ISSUE THREAD

**Issue by jamessding** [jamessding/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search for nearby restaurants using filters.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users can filter restaurants by pricing, distance, and type of food.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="225" alt="Screen Shot 2022-06-15 at 12 46 57 PM" src="https://user-images.githubusercontent.com/103629526/173915850-d73aac84-c0dc-4665-86f8-88604a6c09fa.png">
<img width="700" alt="Screen Shot 2022-06-15 at 12 47 15 PM" src="https://user-images.githubusercontent.com/103629526/173915859-70fb2f93-c755-411f-a465-47a1a6c2a9be.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create webpage design using HTML and CSS.
- [x] Create a form element which contains pricing, distance, and type of food inputs, as well as submit buttons.
- [x] Make sure buttons change colors when clicked.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
