### ISSUE TITLE
Feature: User can view a list of search results.

### ISSUE THREAD

**Issue by jamessding** [jamessding/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a list of search results.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
User can view a list of restaurants that match the filter constraints.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/103629526/173954732-a79076df-f363-4111-a566-bddee8f7e702.png)
![image](https://user-images.githubusercontent.com/103629526/173954772-98506713-bfc8-4f98-bf2f-aabd9ed84eeb.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add [data-view] divs for each view.
- [x] Add an empty unordered list to the `div[data-view="results"]` element in the HTML.
- [x] Add some dummy journal entries to the unordered list in the HTML and style them to match the wireframe.
- [x] Check that the entries list looks good on both mobile and desktop screens.
- [x] Create a new XHR object to send the request and get the HTTP response parsed into JS objects.
- [x] Make sure the GET request's parameters are changing based on user's filter inputs.
- [x] Create a renderResult function that creates a DOM tree for one result in the data model.
- [x] Use a for loop to render each result in the data model and append each to the DOM tree when user clicks Show All Results button.
- [x] Remove the example HTML results once the user's entries are successfully being appended
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
