### ISSUE TITLE
Feature: User can view details of a single restaurant.

### ISSUE THREAD

**Issue by jamessding** [jamessding/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view details of a single restaurant.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click on an individual restaurant card and view more information on that specific restaurant.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-06-17 at 1 24 58 PM](https://user-images.githubusercontent.com/103629526/174396743-a873a89d-f1c8-4c8d-93dd-be1a417790d7.png)
![Screen Shot 2022-06-17 at 1 26 34 PM](https://user-images.githubusercontent.com/103629526/174396747-6d508fc9-615f-47d8-8038-d36ad988c545.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] send an API request for details of a specific restaurant using its unique id in the url
- [x] store the returned object in data model for currentRestaurant property
- [x] render another card which includes location, hours, and phone number and append it to unordered list
- [x] hide all other restaurant cards and change title to 'Restaurant Details'
- [x] add a button to go back to results, which removes the newly created information card and unhides the other restaurant cards
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
