### ISSUE TITLE
Feature: User can save a restaurant to their favorites list.

### ISSUE THREAD

**Issue by jamessding** [jamessding/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can save a restaurant to their favorites list.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click on the heart plus icon next to a restaurant to add the specific restaurant to their favorites list.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-06-22 at 12 44 14 PM](https://user-images.githubusercontent.com/103629526/175123336-4ccbf792-7b82-44f7-b142-b9f5e2c634ed.png)
![Screen Shot 2022-06-22 at 12 46 14 PM](https://user-images.githubusercontent.com/103629526/175123354-c97c8989-d886-4400-9b16-5a24c66ebc5b.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] add a save icon to each rendered restaurant card
- [x] add an Event Listener with 'click' type which saves restaurant into favorite's array of data model
- [x] change icon on card to saved icon when added to favorites list
- [x] add functionality so that clicking saved icon will remove restaurant from favorite's array of data model
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
