### ISSUE TITLE
Feature: User can view their favorites list.

### ISSUE THREAD

**Issue by jamessding** [jamessding/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their favorites list.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click on Favorites on nav bar to view their favorites list.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-06-22 at 4 56 11 PM](https://user-images.githubusercontent.com/103629526/175179752-940eb201-839e-4df5-b8e1-d736d140cd13.png)

![Screen Shot 2022-06-22 at 4 55 33 PM](https://user-images.githubusercontent.com/103629526/175179748-5acfd707-5171-4af1-ba9b-07257d4da663.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] add Favorites link to the nav bar
- [x] add event listener type 'click' which changes title to 'Favorites List'
- [x] add functionality to render restaurants from favorites property of data model
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
